package nl.hva.kieskeurig.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a forum post entity stored in the database.
 * Includes fields for title, content, and author ID.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Data
@Table(name = "posts")
public class Post {

    /**
     * The unique identifier for the post.
     * This is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The title of the post.
     */
    @Column
    private String title;

    /**
     * The main content or body of the post.
     */
    private String content;

    /**
     * The ID of the user who authored the post.
     */
    private int authorId;

    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL)
    @JsonManagedReference
    private List<Comment> comments = new ArrayList<>();


}